// Export all constants from a single entry point

// Default values
export {
  DEFAULT_PROJECT_SETTINGS,
  CANVAS_PRESETS,
  FPS_OPTIONS,
  DEFAULT_FPS,
  DEFAULT_EDITOR_STATE,
  DEFAULT_PLAYBACK_STATE,
  PLAYBACK_SPEEDS,
  DEFAULT_VIEWPORT_STATE,
  MIN_ZOOM,
  MAX_ZOOM,
  ZOOM_STEP,
  ZOOM_LEVELS,
  DEFAULT_UI_STATE,
  PANEL_DIMENSIONS,
  DEFAULT_GRID_CONFIG,
  DEFAULT_RULER_CONFIG,
  TIMELINE_DEFAULTS,
  SNAP_THRESHOLD,
  SELECTION_HANDLE_SIZE,
  DEFAULT_TRANSFORM,
  DEFAULT_ELEMENT_STYLE,
  DEFAULT_TEXT_PROPERTIES,
  AVAILABLE_FONTS,
  DEFAULT_SHAPE_PROPERTIES,
  DEFAULT_FILTER_VALUES,
  DEFAULT_TRANSITION_DURATION,
  DEFAULT_ANIMATION_DURATION,
  DEFAULT_EASING,
  MAX_HISTORY_SIZE,
  AUTO_SAVE_INTERVAL,
  MAX_AUTO_SAVE_VERSIONS,
  DEFAULT_EXPORT_SETTINGS,
  MAX_FILE_SIZE,
  MAX_IMAGE_DIMENSION,
  SUPPORTED_IMAGE_FORMATS,
  SUPPORTED_VIDEO_FORMATS,
  SUPPORTED_AUDIO_FORMATS,
  PERFORMANCE,
  MIN_LAYER_ORDER,
  MAX_LAYER_ORDER,
  COLOR_PALETTE,
  TRACK_TYPE_COLORS,
  NOTIFICATION_DURATION,
  CURSORS,
  APP_VERSION,
  PROJECT_VERSION,
  STORAGE_KEYS,
} from './defaults';

// Keyboard shortcuts
export {
  KEYBOARD_SHORTCUTS,
  SHORTCUT_MAP,
  SHORTCUTS_BY_CATEGORY,
  CATEGORY_NAMES,
  createShortcutKey,
  matchesShortcut,
  getShortcutText,
} from './shortcuts';

export type { KeyboardShortcut } from './shortcuts';

// Presets
export {
  RESOLUTION_PRESETS,
  QUALITY_PRESETS,
  EXPORT_PRESETS,
  PROJECT_TEMPLATES,
  ANIMATION_PRESETS,
  TRANSITION_PRESETS,
  FILTER_PRESETS,
  CODEC_OPTIONS,
  AUDIO_BITRATE_OPTIONS,
  AUDIO_SAMPLE_RATES,
} from './presets';
